pipeline {
  agent any {
    docker { 
        image 'node:16-alpine'
        label 'docker'
         }
  }
  stages {
    stage('Test') {
      steps {
        sh 'node --version'
      }
    }
  }
}